language: objective-c
osx_image: xcode10.1
before_install:
  - brew update

  # Only if app has Carthage dependencies
  - carthage bootstrap --verbose

script:
  - carthage build --no-skip-current
  - |
    xcodebuild test \
    -project AromaSwiftClient/AromaSwiftClient.xcodeproj \
    -scheme AromaSwiftClient \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
